config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get '/auth/:provider/callback', to: 'sessions#twitter_create'
  get 'rankings/like', to: 'rankings#like'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup',to: 'users#create'
  delete 'remove_image', to: 'comments#remove_image'

  resources :users, only: %w[show create edit update] do
    get 'follows', to: 'users#follows'
    get 'followers', to: 'users#followers'
    get 'userlikes', to: 'users#userlikes', as: 'likes'
    get 'userposts', to: 'users#userposts', as: 'posts'
  end

  resources :restaurants, only: %w[show new] do
    resources :comments, only: %w[new create destroy edit update]
  end

  resources :likes, only: %w[create destroy]
  resources :charges, only: %w[new create]
  resources :relationships, only: %w[create destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
  validates :comment, length: { maximum: 300 }
  validates :rating, presence: true, length: { minimum: 1 }
  has_many_attached :images

  delegate :avatar, to: :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :require_user_logged_in
    before_action :set_restaurant, only: %w(new create)

    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @comments = Comment.all.order('created_at DESC').limit(5).with_attached_images
    end

    def create
        comment = @restaurant.comments.new(comment_params)
        comment.user_id = current_user.id
        if comment.save
            flash[:success] = 'コメントを投稿しました！'
            redirect_to @restaurant
        else
            flash[:danger] = "投稿に失敗しました"
            redirect_back(fallback_location: root_path)
        end
    end

    def destroy
        comment = Comment.find(params[:id])
        comment.destroy
        flash[:success] = "コメントを削除しました"
        redirect_back(fallback_location: root_path)
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    def update
        comment= Comment.find(params[:id])
        if comment.update(comment_params)
            flash[:success] = 'コメントを修正しました。'
            redirect_to restaurant_path(comment.restaurant)
        else
            flash[:danger] = 'コメントの修正に失敗しました。'
            redirect_back(fallback_location: root_path)
        end
    end

    def remove_image
        image = ActiveStorage::Attachment.find(params[:remove_id])
        image.purge
        redirect_back(fallback_location: root_path)
    end

private

    def comment_params
        params.require(:comment).permit(:restaurant_id, :user_id, :comment, :rating, images:[])
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
end

app/views/comments/_comment.html.erb
<% if comment %>
  <div class="comment-container">
    <div class='comment-top'>
      <%= link_to(comment.user,class:'comment-link') do %>
        <div class="comment-icons">
          <% if comment.user.avatar.attached? %>
            <div class="user-icon"><%= image_tag(comment.user.avatar.variant(resize: '55x55!'))%></div>
          <%else%>
            <div class="user-icon"><img src="<%= gravatar_url(comment.user,size: 55) %>"></div>
          <%end%>
          <div class="comment-name">
            <div><%= comment.user.name %></div>
            <div class="star-rating" data-score= <%= comment.rating %>></div>
          </div>
        </div>
      <%end%>
      <div class="chat-box">
        <%= simple_format(comment.comment) %>
      </div>
    </div>
    <div class="comment-images">
      <% if comment.images.attached? %>
        <% comment.images.each do |image|%>
          <span class="comment_each_image">
            <%= image_tag image.variant(resize: "150x150!") %>
            <% if current_user == comment.user %>
              <%= link_to remove_image_path(remove_id: image),method: :delete,data:{ confirm: "画像を削除してよろしいですか？"} do %>
                <button class="image_remover">&times;</button>
              <% end %>
            <% end %>
          </span>
        <%end%>
      <% end %>
    </div>
    <div class="comment_bottom">
        <i class="far fa-calendar-alt"></i><span><%= comment.created_at.to_s(:datetime_jp) %></span>
        <% if comment.user == current_user %>
          <%= link_to edit_restaurant_comment_path(comment.restaurant_id,comment),class: 'btn btn-success btn-sm' do %><i class="fas fa-edit"></i><%end%>
          <%= link_to restaurant_comment_path(comment.restaurant_id,comment), method: :delete, data: { confirm: '削除してよろしいですか？' },class: 'btn btn-danger' do %><i class="fas fa-trash-alt"></i><%end%>
        <% end %>
    </div>
  </div>
<% end %>

<script>
  $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/comments/_comment_form.html.erb
<div class="p-comment__formBox">
  <%= form_with(model: comment) do |f| %>
    <%= f.hidden_field :restaurant_id %>
    <div class="comment_form">
      <%= f.label :comment, '記入' %>
      <%= f.text_area :comment, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<div class="new-restaurant_container row">
  <div class="new-restaurant_top col-sm-5">
    <%= form_with(model: @comment,method: :patch,url: restaurant_comment_path) do |f|%>
        <div class="new-restaurant_form">
          <div id="star-rating" class="new-rating"></div>
          <%= f.text_area :comment,class:'new-restaurant_comment' %>
        </div>
        <div class="new-restaurant_img">
          <%= f.label :images, '画像を追加  ( 複数選択可能 )' %>
          <%= f.file_field :images, multiple: true,id:"images" %>
        </div>
        <div id="preview" style="display:none"></div>
        <%= f.submit '投稿する！' ,class:'btn btn-primary' %>
    <%end%>
  </div>
</div>

<%= javascript_include_tag "preview.js" %>

app/views/comments/new.html.erb
<div class="new-restaurant_container row">
  <div class="new-restaurant_top col-sm-5">
    <%= form_with(model:@restaurant.comments.new,url: restaurant_comments_path) do |f|%>
        <h2><%= @restaurant.name %></h2>
        <div class="new-restaurant_form">
          <div id="star-rating" class="new-rating"></div>
          <%= f.text_area :comment,class:'new-restaurant_comment', cols: 40 %>
        </div>
        <div class="new-restaurant_img">
          <%= f.label :images, '投稿画像  ( 複数選択可能 )' %>
          <%= f.file_field :images, multiple: true,id:"images" %>
        </div>
        <div id="preview" style="display:none"></div>
        <%= f.submit '投稿する！' ,class:'btn btn-primary' %>
    <%end%>
  </div>
  <div class="recent-comments scroll col-sm-3">
    <h3>最近のレビュー</h3>
    <%= render @comments %>
  </div>
</div>

<%= javascript_include_tag "preview.js" %>