config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get '/auth/:provider/callback', to: 'sessions#twitter_create'
  get 'rankings/like', to: 'rankings#like'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup',to: 'users#create'
  delete 'remove_image', to: 'comments#remove_image'

  resources :users, only: %w[show create edit update] do
    get 'follows', to: 'users#follows'
    get 'followers', to: 'users#followers'
    get 'userlikes', to: 'users#userlikes', as: 'likes'
    get 'userposts', to: 'users#userposts', as: 'posts'
  end

  resources :restaurants, only: %w[show new] do
    resources :comments, only: %w[new create destroy edit update]
  end

  resources :likes, only: %w[create destroy]
  resources :charges, only: %w[new create]
  resources :relationships, only: %w[create destroy]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name:"User"

    validates :user_id,presence: true
    validates :follow_id,presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in, :set_user
  def create
    relationship = current_user.follow(@user)
    if relationship.save!
      flash[:success] = 'フォローしました！'
      recent_page
    else
      flash[:danger] = 'フォロー失敗しました'
      recent_page
    end
  end

  def destroy
    if current_user.unfollow(@user)
      flash[:success] = 'フォローを外しました！'
      recent_page
    else
      flash[:danger] = 'フォロー失敗しました'
      recent_page
    end
  end

  private

  def set_user
    @user = User.find(params[:follow_id])
  end

  def recent_page
    redirect_back(fallback_location: root_path)
  end
  
end

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
    <% if current_user.following?(user) %>
        <%= form_with url: relationship_path(user),method: :delete do |f|  %>
            <%= hidden_field_tag :follow_id, user.id %>
            <span class="following_button"><i class="fas fa-check"></i><input type="submit" name="commit" value="Following" class="following" data-disable-with="送信中"></span>
        <% end %>
    <%else%>
        <%= form_with url: relationships_path,method: :post do |f|  %>
            <%= hidden_field_tag :follow_id, user.id %>
            <span class="following_button"><i class="fas fa-check" style=color:#4c5b66;></i><input type="submit" name="commit" value="Follow" class="follow" data-disable-with="送信中"></span>
        <% end %>
    <%end%>
<%end%>