config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get '/auth/:provider/callback', to: 'sessions#twitter_create'
  get 'rankings/like', to: 'rankings#like'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup',to: 'users#create'
  delete 'remove_image', to: 'comments#remove_image'

  resources :users, only: %w[show create edit update] do
    get 'follows', to: 'users#follows'
    get 'followers', to: 'users#followers'
    get 'userlikes', to: 'users#userlikes', as: 'likes'
    get 'userposts', to: 'users#userposts', as: 'posts'
  end

  resources :restaurants, only: %w[show new] do
    resources :comments, only: %w[new create destroy edit update]
  end

  resources :likes, only: %w[create destroy]
  resources :charges, only: %w[new create]
  resources :relationships, only: %w[create destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  has_one_attached :avatar
  validates :name, presence: true, length: { minimum: 3, maximum: 10 }
  validates :email, presence: true, length: { maximum: 50 },uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 4 }, on: :create
  validates :profile, length: { maximum: 200 }
  has_secure_password

  has_many :likes, dependent: :destroy
  has_many :restaurants, through: :likes
  has_many :like_restaurants, through: :likes, source: :restaurant
  has_many :comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :followings,through: :relationships,source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id',dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    self.relationships.find_or_create_by(follow_id:other_user[:id]) unless self == other_user
  end

  def unfollow(other_user)
    self.relationships.find_by(follow_id: other_user[:id]).destroy unless self == other_user
  end

  def following?(other_user)
    self.followings.include?(other_user) unless self == other_user
  end

  def like(restaurant)
    likes.find_or_create_by(restaurant_id: restaurant.id)
  end

  def unlike(restaurant)
    likes.find_by(restaurant_id: restaurant.id).destroy
  end

  def like?(restaurant)
    like_restaurants.include?(restaurant)
  end

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    image = auth[:info][:image]

    self.find_or_create_by(provider: provider,uid: uid) do |user|
      user.email = 'aiueo@gmail.com'
      user.password = 'aiueo12345'
      user.name = name
      user.image = image
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, except: %w[new create]
  before_action :set_user, only: %w[show edit update]
  before_action :set_nest_user, only: %w[follows followers userlikes userposts]

  def new
    @user = User.new
  end

  def show; end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザの登録をしました。'
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'プロフィールを編集しました！'
      redirect_to @user
    else
      flash[:danger] = '編集に失敗しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  def follows
    @follows = @user.followings.with_attached_avatar
  end

  def followers
    @followers = @user.followers.with_attached_avatar
  end

  def userlikes
    @restaurants = @user.restaurants
  end

  def userposts
    @comments = @user.comments.includes(:restaurant).with_attached_images
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :profile, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_nest_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mm"
  end
end

app/views/users/_sidebar.html.erb
<div class="col-sm-3">
    <div class="menu">
        <ul>
        <%= link_to user_path(user) do %><li><span class="fa fa-home"></span>home</li><%end%>
        <% if current_user == user %>
            <%= link_to edit_user_path(user) do %><li><span class="fas fa-edit"></span>プロフィール編集</li><%end%>
        <% end %>
        <%= link_to user_follows_path(user) do %><li><span class="fas fa-users"></span>フォロー</li><%end%>
        <%= link_to user_followers_path(user) do %><li><span class="fas fa-users"></span>フォロワー</li><%end%>
        <%= link_to user_likes_path(user) do %><li><span class="far fa-thumbs-up"></span>お気に入り一覧</li><%end%>
        <%= link_to user_posts_path(user) do %><li><span class="fas fa-check"></span>投稿一覧</li><%end%>
        <% if current_user == user %>
            <%= link_to logout_path, method: :delete do %><li class="logout"><span class="fas fa-sign-out-alt"></span>ログアウト</li><%end%>
        <% end %>
        </ul>
    </div>
</div>

app/views/users/edit.html.erb
<%content_for :cover do%>
  <div class="mypage_cover">
    <div class="container">
      <div class="row">
        <%= render 'sidebar',user: @user %>
        <div class="col-sm-8">
          <div class="mypage edit-user_page">
            <h3 class="edit-user_title text-center">プロフィール編集</h3>
            <%= form_with model: @user,method: :patch do |f| %>
              <div class="form-group row">
                <%= f.label :image, class: 'col-xs-3 text-right edit-user_label' %>
                <% if @user.avatar.attached? %>
                  <div class="col-xs-3"><%= image_tag(@user.avatar.variant(resize: '100x100!')) %></div>
                <% else %>
                  <div class="col-xs-3"><img src="<%= gravatar_url(@user,size: 100) %>"></div>
                <% end %>
                <%= f.file_field :avatar %>
              </div>
              <div class="form-group row">
                <%= f.label :name, class: 'col-xs-3 text-right edit-user_label' %>
                <%= f.text_field :name, class: 'form-effect col-xs-8',placeholder: "名前" %>
              </div>
              <div class="form-group row">
                <%= f.label :email, class: 'col-xs-3 text-right edit-user_label' %>
                <%= f.email_field :email, class: 'form-effect col-xs-8',placeholder: "Email" %>
              </div>
              <div class="form-group row">
                <%= f.label :profile, class: 'col-xs-3 text-right edit-user_label' %>
                <%= f.text_area :profile, class: 'form-effect form-area col-xs-8',placeholder: "プロフィール" %>
              </div>
              <div class="text-center"><%= f.submit '変更する',class: 'edit-user_submit' %></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/users/followers.html.erb
<%content_for :cover do%>
  <div class="mypage_cover">
    <div class="container">
      <div class="row">
        <%= render 'sidebar',user: @user %>
        <div class="col-sm-8 col-sm-offset-1">
          <h2 class="text-center follow_and_follower_title" style="font-family:HiraKakuStdN-W8;">Follower</h2>
          <div class="row follow_and_follower_container">
            <% @followers.each do |follow|%>
              <%= link_to user_path(follow) do %>
                <div class="flex col-sm-5 follow_and_follower">
                  <div class="follow_image">
                    <% if follow.avatar.attached? %>
                      <%= image_tag(follow.avatar.variant(resize: '75x75!')) %>
                    <% else %>
                      <img src="<%= gravatar_url(follow,size: 75) %>">
                    <% end %>
                  </div>
                  <div class="follow_desc">
                    <p class="follow_name"><%= follow.name %></p>
                    <span class="follow_comment"><%= follow.comments.count %></span><span>comments</span><span class="follow_count"><%= @user.followers.count %></span><span>followers</span>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/users/follows.html.erb
<%content_for :cover do%>
  <div class="mypage_cover">
    <div class="container">
      <div class="row">
        <%= render 'sidebar',user: @user %>
        <div class="col-sm-8 col-sm-offset-1">
          <h2 class="text-center follow_and_follower_title" style="font-family:HiraKakuStdN-W8;">Follow</h2>
          <div class="row follow_and_follower_container">
            <% @follows.each do |follow|%>
              <%= link_to user_path(follow) do %>
                <div class="flex col-sm-5 follow_and_follower">
                  <div class="follow_image">
                    <% if follow.avatar.attached? %>
                      <%= image_tag(@user.avatar.variant(resize: '75x75!')) %>
                    <% else %>
                      <img src="<%= gravatar_url(follow,size: 75) %>">
                    <% end %>
                  </div>
                  <div class="follow_desc">
                    <p class="follow_name"><%= follow.name %></p>
                    <span class="follow_comment"><%= follow.comments.count %></span><span>comments</span><span class="follow_count"><%= @user.followers.count %></span><span>followers</span>
                  </div>
                </div>
              <%end%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/users/new.html.erb
<% content_for(:cover) do %>
<div class="sign-body">
  <div class="model-dialog text-center">
    <div class="main-section col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4">
      <div class="model-content">
        <div class="col-12 user-img">
          <i class="fab fa-gofore"></i>
        </div>
        <%= form_with model: @user,url: signup_path do |f| %>
          <%= render 'layouts/error_messages', model: f.object%>
          <form class="col-12">
            <div class="form-login">
              <%= f.text_field :name, class: 'form-control',placeholder: "Username" %>
            </div>
            <div class="form-login email">
              <%= f.text_field :email, class: 'form-control',placeholder: "Email" %>
            </div>
            <div class="form-login password">
              <%= f.text_field :password, class: 'form-control',placeholder: "Password" %>
            </div>
            <div class="form-login password">
              <%= f.text_field :password_confirmation, class: 'form-control',placeholder: "Password(確認)" %>
            </div>
            <div class="form-avatar">
              <i class="fas fa-image avatar-icon"></i><%= f.file_field :avatar%>
            </div>
            <button type="submit" class="btn-signin"><i class="fas fa-sign-in-alt"></i>登録する</button>
            <p class="or">or</p>
            <button type="submit" class="btn-tweet-signin"><i class="fab fa-twitter"></i>Twitterでログイン</button>
          </form>
        <% end %>
      </div> <!-- end of cotent -->
    </div>
  </div>
</div>
<%end%>

app/views/users/show.html.erb
<%content_for :cover do%>
  <div class="mypage_cover">
    <div class="container">
      <div class="row">
        <%= render 'sidebar',user: @user %>
        <div class="col-sm-8">
          <div class="mypage">
            <div class="user-profile row">
              <div class="show-user_image col-xs-4">
                <% if @user.avatar.attached? %>
                  <%= image_tag(@user.avatar.variant(resize: '200x200!')) %>
                <% else %>
                  <img src="<%= gravatar_url(@user,size: 200) %>">
                <% end %>
                <p class="show-user_follow_button"><%= render 'relationships/follow_button',user: @user %></p>
              </div>
              <div class="show-name_desc col-xs-7">
                <div class="show-user_relation flex">
                  <h2 class="show-user_name"><%= @user.name %></h2>
                  <div class="relation_count">
                    <span class="show-user_follow"><span><%= @user.followings.count %></span>follow</span>
                    <span class="show-user_follower"><span><%= @user.followers.count%></span>follower</span>
                  </div>
                </div>
                <% if @user.profile %>
                  <h3>プロフィール</h3>
                  <div class="profile">
                    <%= simple_format(@user.profile) %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
       </div>
    </div>
  </div>
<%end%>

app/views/users/userlikes.html.erb
<%content_for :cover do%>
  <div class="mypage_cover">
    <div class="container">
      <div class="row">
        <%= render 'sidebar',user: @user %>
        <div class="col-sm-8 col-sm-offset-1">
          <h2 class="text-center follow_and_follower_title" style="font-family:HiraKakuStdN-W8; color:darkorange;">お気に入り一覧</h2>
          <div class="row follow_and_follower_container">
            <% @restaurants.each do |restaurant|%>
              <%= link_to restaurant_path(restaurant) do %>
                <div class="flex col-sm-5 follow_and_follower">
                  <div class="follow_image">
                    <%= image_tag(restaurant.shop_image1) %>
                  </div>
                  <div class="follow_desc">
                    <p class="follow_name"><%= restaurant.name %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/users/userposts.html.erb
<%content_for :cover do%>
  <div class="mypage_cover">
    <div class="container">
      <div class="row">
        <%= render 'sidebar',user: @user %>
        <div class="col-sm-8 col-sm-offset-1">
          <h2 class="text-center follow_and_follower_title" style="font-family:HiraKakuStdN-W8; color:darkorange;">口コミ投稿したお店一覧</h2>
          <div class="row follow_and_follower_container">
          <% @comments.each do |comment| %>
            <%= link_to restaurant_path(comment.restaurant) do %>
              <div class="flex col-sm-5 userposts_comment">
                <div class="follow_image">
                  <% if comment.images.attached? %>
                    <%= image_tag comment.images.first %>
                  <% else %>
                    <img src='https://ximg.retty.me/crop/s172x172/-/retty_main/images/noimg_200_150.png'>
                  <% end %>
                </div>
                <div class="userposts_desc">
                  <p class="userposts_restaurant_title"><%= comment.restaurant.name %></p>
                  <p class="fas fa-comment-dots comment_effect"><%= comment.comment %></p>
                </div>
              </div>
            <% end %>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

<script>
  $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>