config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get '/auth/:provider/callback', to: 'sessions#twitter_create'
  get 'rankings/like', to: 'rankings#like'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup',to: 'users#create'
  delete 'remove_image', to: 'comments#remove_image'

  resources :users, only: %w[show create edit update] do
    get 'follows', to: 'users#follows'
    get 'followers', to: 'users#followers'
    get 'userlikes', to: 'users#userlikes', as: 'likes'
    get 'userposts', to: 'users#userposts', as: 'posts'
  end

  resources :restaurants, only: %w[show new] do
    resources :comments, only: %w[new create destroy edit update]
  end

  resources :likes, only: %w[create destroy]
  resources :charges, only: %w[new create]
  resources :relationships, only: %w[create destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class = "alert alert-warning">
        <ul>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if flash[:success] %>
  <div class="alert alert-success">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><i class="far fa-check-circle"></i><%= flash[:success] %></strong>
  </div>
<% elsif flash[:danger] %>
  <div class="alert alert-danger center-block">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <strong><i class="fas fa-exclamation-circle"></i><%= flash[:danger]%></strong>
  </div>
<% elsif flash[:notice] %>
  <div class="alert alert-info">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%= flash[:notice]%>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted">gnavi</div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar">
    <div class="container-fluid">
      <!-- Nav Header -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-1" aria-expanded="false">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><span class="fab fa-gofore" style="font-size:30px;"></span>navi</a>
      </div>
      <div class="navbar-collapse collapse" id="collapse-1">
        <!-- Nav Left -->
        <ul class="nav navbar-nav">
          <% if logged_in? %>
            <li><%= link_to (user_path(current_user)) do %><span class="fas fa-user-cog"></span><span class="link">マイページ</span><%end%></li>
            <li><a href="/rankings/like"><span class="fas fa-crown"></span><span class="link">Ranking</span></a></li>
          <% else %>
            <li><%= link_to 'SignUp',signup_path %></li>
            <li><%= link_to 'Login',login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gnavi</title>
    <%= csrf_meta_tags %>
    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- fontawesome -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield :cover %>
    <div class="container">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>